version: '3.7'
services:
  spring:
    image: openjdk:8-jdk-alpine
    container_name: roulette
    volumes:
      - .:/home/ruleta 
    environment: 
      - RedisURL=172.17.0.1
      - RedisPort=6379
    ports:
      - 8080:8080
    working_dir: /home/ruleta   
    depends_on:
      - redis
    command: sh -c 'ls;./mvnw spring-boot:run'  
  redis:
    container_name: roulette-redis
    image: redis:latest
    ports:
    - 6379:6379
    command:
    - redis-server
    - --appendonly
    - 'yes'
    volumes:
    - .:/data